
: LCD_WELCOME
    s" X ATTIVARE PREMI" LCDTYPE 
    NEWLINE
    s" IL PULSANTE BLU" LCDTYPE
;

: NUMBER2LCD
    DUP 10 /  48 +  LCDEMIT
    DUP 10 mod  48 +  LCDEMIT
    37 LCDEMIT
;

: DRY_SOIL  
    s" ASCIUTTO   " LCDTYPE DRY
    NEWLINE
    s" LIV. ACQUA: " LCDTYPE  NUMBER2LCD
;

: PERFECT_SOIL 
    PLANT s" CONDIZIONI OK " LCDTYPE PLANT
    NEWLINE
    s" LIV. ACQUA: " LCDTYPE  NUMBER2LCD
;

: WET_SOIL 
    s" BAGNATO   " LCDTYPE WET
    NEWLINE
    s" LIV. ACQUA: " LCDTYPE  NUMBER2LCD
;

: MEAN  
    adc1 dr @  
    1000 1 DO adc1 dr @ + LOOP  
    1000 / 
;

: ?VALUE 
    START_CONVERSION 
    MEAN  
    99 *  4095 /
;

: ?MOISTURE
   CLEAN_LCD 
   DUP 80 > IF  WET_SOIL      ELSE
   DUP 40 > IF  PERFECT_SOIL  ELSE
                DRY_SOIL
   THEN THEN DROP
;

: INIT 
    LCD_INIT 
    LCD_WELCOME
    ADC_INIT
    BUTTON CLICKED 
    BEGIN  ADC_ON ?VALUE ADC_OFF ?MOISTURE 1m DELAY  AGAIN
;

INIT
